language: rust

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

matrix:
  include:

    # GNU/Linux - Rust Stable Test
    - env: TARGET=x86_64-unknown-linux-gnu
      name: Cargo Test
      rust: stable
      script: ./test.sh

    # GNU/Linux - Deploy Clique Network
    - env: TARGET=x86_64-unknown-linux-gnu
      name: Cargo Test
      rust: stable
      script: ./clique.sh

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

before_script:
  - rustup self update
  - source ~/.cargo/env || true

after_success: |
  echo "@TODO"
