language: rust
sudo: required
services: docker

addons:
  apt:
    packages:
      - binutils-dev
      - cmake
      - file
      - g++
      - gcc
      - libcurl4-openssl-dev
      - libdw-dev
      - libelf-dev
      - libiberty-dev
      - libudev-dev
      - make
      - pkg-config

matrix:
  include:

    # GNU/Linux - Rust Stable Test
    - env: TARGET=x86_64-unknown-linux-gnu
      name: Cargo Test Rust Stable
      rust: stable
      script:
        - $TRAVIS_BUILD_DIR/scripts/validate_chainspecs.sh
        - cargo test --features json-tests,ci-skip-issue,final --all

    # GNU/Linux - Deploy Görli Node
    - env: TARGET=x86_64-unknown-linux-gnu
      name: Deploy Goerli Node
      rust: stable
      script:
        - cargo build --features final
        - $TRAVIS_BUILD_DIR/target/debug/parity --chain goerli --log-file $TRAVIS_BUILD_DIR/parity.log & sleep 1200 && killall parity

    # GNU/Linux - Deploy Clique Network
    - env: TARGET=x86_64-unknown-linux-gnu
      name: Deploy Clique Network
      rust: stable
      script:
        - $TRAVIS_BUILD_DIR/clique.sh
        - $TRAVIS_BUILD_DIR/parity-deploy/clean.sh

cache:
  - rust
  - cargo
  - $HOME/.cargo
  - $HOME/.rustup
  - $TRAVIS_BUILD_DIR/target

before_cache:
  - chmod -R a+r $HOME

before_script:
  - rustup self update
  - source ~/.cargo/env || true
